In [118]:
import pandas as pd
from pandas import DataFrame,Series
import numpy as np

In [23]:
df=pd.read_csv("train.csv")

In [24]:
df.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [26]:
df.drop(["Name","Ticket","Cabin"],axis=1,inplace= True)

In [27]:
df.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    male  22.0      1      0   7.2500        S
1            2         1       1  female  38.0      1      0  71.2833        C
2            3         1       3  female  26.0      0      0   7.9250        S
3            4         1       1  female  35.0      1      0  53.1000        S
4            5         0       3    male  35.0      0      0   8.0500        S

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Fare           891 non-null float64
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(2)
memory usage: 62.7+ KB


In [28]:
df.dropna(inplace=True)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 9 columns):
PassengerId    712 non-null int64
Survived       712 non-null int64
Pclass         712 non-null int64
Sex            712 non-null object
Age            712 non-null float64
SibSp          712 non-null int64
Parch          712 non-null int64
Fare           712 non-null float64
Embarked       712 non-null object
dtypes: float64(2), int64(5), object(2)
memory usage: 55.6+ KB


In [31]:
df.Sex.value_counts()

male      453
female    259
Name: Sex, dtype: int64

In [32]:
df["Gender"]=df.Sex.map({"male":1,"female":0})

In [33]:
df.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0            1         0       3    male  22.0      1      0   7.2500   
1            2         1       1  female  38.0      1      0  71.2833   
2            3         1       3  female  26.0      0      0   7.9250   
3            4         1       1  female  35.0      1      0  53.1000   
4            5         0       3    male  35.0      0      0   8.0500   

  Embarked  Gender  
0        S       1  
1        C       0  
2        S       0  
3        S       0  
4        S       1

In [34]:
df.Embarked.value_counts()

S    554
C    130
Q     28
Name: Embarked, dtype: int64

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 11 columns):
PassengerId    712 non-null int64
Survived       712 non-null int64
Pclass         712 non-null int64
Sex            712 non-null object
Age            712 non-null float64
SibSp          712 non-null int64
Parch          712 non-null int64
Fare           712 non-null float64
Embarked       712 non-null object
Gender         712 non-null int64
Port           712 non-null int64
dtypes: float64(2), int64(7), object(2)
memory usage: 66.8+ KB


In [36]:
df["Port"]=df.Embarked.map({"S":1,"C":2,"Q":3})

In [39]:
df.drop(["Sex","Embarked"],axis=1,inplace=True)

ValueError: labels ['Sex' 'Embarked'] not contained in axis

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 9 columns):
PassengerId    712 non-null int64
Survived       712 non-null int64
Pclass         712 non-null int64
Age            712 non-null float64
SibSp          712 non-null int64
Parch          712 non-null int64
Fare           712 non-null float64
Gender         712 non-null int64
Port           712 non-null int64
dtypes: float64(2), int64(7)
memory usage: 55.6 KB


In [79]:
cols=df.columns.tolist()
df.head()

PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare  Gender  Port
0            1         0       3  22.0      1      0   7.2500       1     1
1            2         1       1  38.0      1      0  71.2833       0     2
2            3         1       3  26.0      0      0   7.9250       0     1
3            4         1       1  35.0      1      0  53.1000       0     1
4            5         0       3  35.0      0      0   8.0500       1     1

In [80]:
cols = cols[1:2] + cols[0:1] + cols[2:]

In [83]:
df=df[cols]
df.head()

Survived  PassengerId  Pclass   Age  SibSp  Parch     Fare  Gender  Port
0         0            1       3  22.0      1      0   7.2500       1     1
1         1            2       1  38.0      1      0  71.2833       0     2
2         1            3       3  26.0      0      0   7.9250       0     1
3         1            4       1  35.0      1      0  53.1000       0     1
4         0            5       3  35.0      0      0   8.0500       1     1

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 0 to 890
Data columns (total 9 columns):
Survived       712 non-null int64
PassengerId    712 non-null int64
Pclass         712 non-null int64
Age            712 non-null float64
SibSp          712 non-null int64
Parch          712 non-null int64
Fare           712 non-null float64
Gender         712 non-null int64
Port           712 non-null int64
dtypes: float64(2), int64(7)
memory usage: 55.6 KB


In [86]:
train_data=df.values

In [87]:
train_data

array([[   0.    ,    1.    ,    3.    , ...,    7.25  ,    1.    ,    1.    ],
       [   1.    ,    2.    ,    1.    , ...,   71.2833,    0.    ,    2.    ],
       [   1.    ,    3.    ,    3.    , ...,    7.925 ,    0.    ,    1.    ],
       ..., 
       [   1.    ,  888.    ,    1.    , ...,   30.    ,    0.    ,    1.    ],
       [   1.    ,  890.    ,    1.    , ...,   30.    ,    1.    ,    2.    ],
       [   0.    ,  891.    ,    3.    , ...,    7.75  ,    1.    ,    3.    ]])

In [90]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=100)

In [93]:
model=model.fit(train_data[:,2:],train_data[:,0])

In [94]:
test=pd.read_csv("test.csv")

In [95]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Name           418 non-null object
Sex            418 non-null object
Age            332 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Ticket         418 non-null object
Fare           417 non-null float64
Cabin          91 non-null object
Embarked       418 non-null object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [97]:
test.drop(["Name","Ticket","Cabin"],axis=1,inplace=True)

In [98]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 8 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Sex            418 non-null object
Age            332 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Fare           417 non-null float64
Embarked       418 non-null object
dtypes: float64(2), int64(4), object(2)
memory usage: 26.2+ KB


In [108]:
test.dropna(inplace=True)
test["Gender"]=test.Sex.map({"male":1,"female":0})
test["Port"]=test.Embarked.map({"S":1,"C":2,"Q":3})
test.drop(["Sex","Embarked"],axis=1, inplace=True)


AttributeError: 'DataFrame' object has no attribute 'Sex'

In [121]:
test.info()
test_data=test.values

<class 'pandas.core.frame.DataFrame'>
Int64Index: 331 entries, 0 to 415
Data columns (total 8 columns):
PassengerId    331 non-null int64
Pclass         331 non-null int64
Age            331 non-null float64
SibSp          331 non-null int64
Parch          331 non-null int64
Fare           331 non-null float64
Gender         331 non-null int64
Port           331 non-null int64
dtypes: float64(2), int64(6)
memory usage: 23.3 KB


In [122]:
output=model.predict(test_data[:,1:])

In [113]:
output

array([ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,
        1.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,
        0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,
        0.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,
        0.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  0.,
        1.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,
        1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
        1.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,
        1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,
        0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,
        0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,
        1.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
        0.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  0

In [127]:
result=np.c_[test_data[:,0].astype(int),output.astype(int)]
result


array([[ 892,    0],
       [ 893,    0],
       [ 894,    0],
       [ 895,    1],
       [ 896,    0],
       [ 897,    0],
       [ 898,    0],
       [ 899,    0],
       [ 900,    1],
       [ 901,    0],
       [ 903,    0],
       [ 904,    1],
       [ 905,    0],
       [ 906,    1],
       [ 907,    1],
       [ 908,    0],
       [ 909,    1],
       [ 910,    0],
       [ 911,    0],
       [ 912,    1],
       [ 913,    0],
       [ 915,    1],
       [ 916,    1],
       [ 917,    0],
       [ 918,    1],
       [ 919,    1],
       [ 920,    0],
       [ 922,    0],
       [ 923,    0],
       [ 924,    1],
       [ 926,    1],
       [ 927,    1],
       [ 929,    0],
       [ 930,    0],
       [ 932,    0],
       [ 934,    0],
       [ 935,    1],
       [ 936,    1],
       [ 937,    0],
       [ 938,    0],
       [ 940,    1],
       [ 941,    1],
       [ 942,    1],
       [ 943,    0],
       [ 944,    1],
       [ 945,    1],
       [ 947,    0],
       [ 948,

In [129]:
result_df= DataFrame(result[:,0:2],columns=["Passenger_id","Survived"])
result_df.head()

Passenger_id  Survived
0           892         0
1           893         0
2           894         0
3           895         1
4           896         0

In [131]:
result_df.shape

(331, 2)

In [132]:
result_df.to_csv("Result.csv",index=False)